Name:           ros-indigo-rqt-action
Version:        0.3.9
Release:        0%{?dist}
Summary:        ROS rqt_action package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/rqt_action
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-indigo-rospy
Requires:       ros-indigo-rqt-msg
Requires:       ros-indigo-rqt-py-common
BuildRequires:  ros-indigo-catkin

%description
rqt_action provides a feature to introspect all available ROS action (from
actionlib) types. By utilizing rqt_msg, the output format is unified with it and
rqt_srv. Note that the actions shown on this plugin is the ones that are stored
on your machine, not on the ROS core your rqt instance connects to.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Mon Aug 18 2014 Isaac Isao Saito <130s@2000.jukuin.keio.ac.jp> - 0.3.9-0
- Autogenerated by Bloom

